maplight/clc-ad-transparency

backend/README.md
Adding instructions to install strapi and setup .env file as these are necessary to run other commands if starting from cloned repo.
=> Adding some additional setup instructions

backend/src/api/filing-period/content-types/filing-period/schema.json, backend/src/api/filing-period/controllers/filing-period.ts, backend/src/api/filing-period/routes/filing-period.ts, backend/src/api/filing-period/services/filing-period.ts
Adds a content type for filing periods with the following attributes:
* name
* endDate
* startDate
[CLCAD-14](https://maplight.atlassian.net/browse/CLCAD-14)
[CLCAD-14]: https://maplight.atlassian.net/browse/CLCAD-14?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] Create filing period CLCAD-14

backend/src/api/ad-disclosure/content-types/ad-disclosure/schema.json, backend/src/api/ad-disclosure/controllers/ad-disclosure.ts, backend/src/api/ad-disclosure/routes/ad-disclosure.ts, backend/src/api/ad-disclosure/services/ad-disclosure.ts, backend/src/components/ad-disclosure/candidates-measures-and-or-political-parties.json
This pull request creates the `adDisclosure` content type with all optional and required fields. The following fields are added to the content type:
* ad format
* ad spend
* target audience
* view count
* click count
* authorized ad spend
* external link
* start date
* end date
* text content
* election
* media
* candidates, measures and/or political parties
The election select field, for the POC, will just be a hard-coded list. Eventually, this would be a custom field that would get available elections from an external system. We should, however, probably add some better hard-coded values here of what a filer may actually see.
The view configuration in Strapi gets saved to the database instead of being configured in code. Therefore, we'll want to update this view to give it a better …
=> [FEATURE] Ad disclosure content type CLCAD-3

backend/package.json, backend/yarn.lock
After merging #11, the Strapi deployment [encountered an error](https://cloud.strapi.io/projects/clc-ad-transparency-99273c2e21/deployments/d1ece413-722a-4b62-91e3-66e8a604461a). The error was caused because the install of dependencies and building of our local plugin was not accounted for. This PR fixes the issue by using yarn workspaces to install dependencies for the main app and the plugin at once as well as updating the build command to build the main app and the plugin consecutively.
* Delete the `dist` and `node_modules` directories for both the main protect and the local plugin
* Run `yarn install` from the `backend` directory to install deps for the main app and the local plugin
* Run `yarn build` to build both the main app and the plugin
* Run `yarn start` to serve the …
=> [BUGFIX] Strapi deployment failure CLCAD-4

backend/patches/@strapi+admin+4.12.7.patch
Users were able to access the welcome page after logging out or when trying to access /admin/auth/** paths directly.  This pr should send them to the content manager instead.
=> [BUG] Patching a few more redirects to the welcome page CLCAD-59

backend/package.json, backend/src/index.ts, backend/src/utils/algolia-client.ts, backend/yarn.lock
Uses `afterCreate` hook to index `adDisclosures` in Algolia when reports are created.
[CLCAD-40](https://maplight.atlassian.net/browse/CLCAD-40)
[CLCAD-40]: https://maplight.atlassian.net/browse/CLCAD-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] Algolia search index CLCAD-40

backend/src/plugins/ad-disclosure-report/admin/src/components/AdDisclosureTable/index.tsx, backend/src/plugins/ad-disclosure-report/admin/src/hooks/use-ad-disclosure-report-data.ts, backend/src/plugins/ad-disclosure-report/admin/src/hooks/use-is-admin.ts, backend/src/plugins/ad-disclosure-report/admin/src/index.tsx, backend/src/plugins/ad-disclosure-report/server/register.ts, backend/types/generated/components.d.ts, backend/types/generated/contentTypes.d.ts
After deploying #18, an internal server error was discovered when indexing ad disclosures to Algolia. The error was caused by the `JSON.parse` call from within the `afterCreate` lifecycle hook. The thrown error was because the `adDisclosures` received in this context were of type `JSON` and not `string` causing the parsing to fail (because the custom field is registered as type `json`). This issue was not caught in local development, because changes were made to the `register` function while running in development with the `--watch-admin` flag. However, the plugin needs to be rebuilt when changes are made to the `register` function which is not apparent in the documentation. Removing the parsing in the `afterCreate` hook fixed the issue with the server error. However, removing the parsing …
=> [BUGFIX] Server error when indexing to Algolia CLCAD-40

backend/package.json, backend/patches/@strapi+admin+4.14.4.patch, backend/src/plugins/ad-disclosure-report/package.json, backend/src/plugins/ad-disclosure-report/yarn.lock, backend/yarn.lock
This PR upgrades all of the Strapi packages to their latest version. This change was made to pull in a [bug fix](https://github.com/strapi/strapi/pull/18153) that allows us to tighten permissions on the media library so that filers only see uploads that they have created.
Permissions for the media library plugin must be updated locally to see this fix reflected. The permissions on production have already been updated, but we should verify after the merge.
[CLCAD-53](https://maplight.atlassian.net/browse/CLCAD-53)
[CLCAD-53]: https://maplight.atlassian.net/browse/CLCAD-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INTERNAL] Upgrade Strapi to latest version

backend/src/api/ad-disclosure/content-types/ad-disclosure/schema.json, backend/types/generated/contentTypes.d.ts
Requires filers to add at least one candidate, measure, or political party when creating an ad disclosure.
[CLCAD-62](https://maplight.atlassian.net/browse/CLCAD-62)
[CLCAD-62]: https://maplight.atlassian.net/browse/CLCAD-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] Require Candidates, Measures, and/or Parties CLCAD-62

backend/src/plugins/ad-disclosure-report/admin/src/index.tsx, backend/src/plugins/ad-disclosure-report/server/register.ts, backend/types/generated/contentTypes.d.ts
After merging #19 to production, I began testing the indexing to Algolia and saw another 500 server error occurring. Digging into the Strapi runtime logs presented a clue to what was going on:
```
[2023-10-25 20:27:48] [2023-10-25 20:27:48.294] error: insert into "public"."reports" ("ad_disclosures", "created_at", "created_by_id", "updated_at", "updated_by_id") values ($1, $2, $3, $4, $5) returning "id" - value too long for type character varying(255)
[2023-10-25 20:27:48] error: insert into "public"."reports" ("ad_disclosures", "created_at", "created_by_id", "updated_at", "updated_by_id") values ($1, $2, $3, $4, $5) returning "id" - value too long for type character varying(255)
```
After looking through some [GitHub issues](https://github.com/strapi/strapi/issues/12130), I realized that …
=> [BUGFIX] 500 internal server error CLCAD-64

backend/.env.example, backend/README.md, frontend/README.md, frontend/app/root.tsx, frontend/app/routes/_index.tsx, frontend/app/search-client.ts, frontend/global.d.ts, frontend/instantsearch.d.ts, frontend/package.json, frontend/utils/get-env.ts, frontend/yarn.lock
Adds basic search functionality by wiring up our frontend Remix app to Algolia InstantSearch. This basic search will return results as a simple JSON string. We will refine this as we move forward with the Algolia components.
[CLCAD-42](https://maplight.atlassian.net/browse/CLCAD-42)
[CLCAD-42]: https://maplight.atlassian.net/browse/CLCAD-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] Initial Algolia frontend search CLCAD-42

backend/src/plugins/ad-disclosure-report/admin/src/components/AdDisclosureTable/index.tsx
Updates the fields listed in the ad disclosure table to include:
* ID
* Ad Election
* Ad Spend
Updates the table rows to navigate to the ad disclosure on click.
[CLCAD-58](https://maplight.atlassian.net/browse/CLCAD-58)
[CLCAD-58]: https://maplight.atlassian.net/browse/CLCAD-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] Ad disclosure fields for reports CLCAD-58

backend/src/plugins/ad-disclosure-report/package.json, backend/src/plugins/ad-disclosure-report/yarn.lock, backend/yarn.lock
After merging #22, a run-time error started occurring in production. This error was caused because when Strapi generated files for the `ad-disclosure-report` plugin, it installed `styled-components` as a dev dependency. However, we need this dependency in production. This PR moves `styled-components` from `devDependencies` and updates to the latest version.
Note: Because we are using yarn workspaces to manage dependencies, you will see updates to both the plugin and root directory's `yarn.lock` files.
[CLCAD-65](https://maplight.atlassian.net/browse/CLCAD-65)
[CLCAD-65]: https://maplight.atlassian.net/browse/CLCAD-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX] Missing dependency on production CLCAD-65

backend/src/index.ts, frontend/app/components/MenuSelect/index.tsx, frontend/app/components/NumericMenu/index.tsx, frontend/app/routes/_index.tsx
This PR extends the frontend capabilities of the Algolia search by providing filtering options for the following fields:
* `adElection`
* `adFormat`
* `adSpend`
* `createdBy`
* `candidatesMeasuresAndPoliticalParties`
https://github.com/maplight/clc-ad-transparency/assets/38389357/efd84a0b-8310-4bcc-9ca3-435c84383ef8
[CLCAD-7](https://maplight.atlassian.net/browse/CLCAD-7)
[CLCAD-17](https://maplight.atlassian.net/browse/CLCAD-17)
[CLCAD-19](https://maplight.atlassian.net/browse/CLCAD-19)
[CLCAD-20](https://maplight.atlassian.net/browse/CLCAD-20)
[CLCAD-21](https://maplight.atlassian.net/browse/CLCAD-21)
[CLCAD-31](https://maplight.atlassian.net/browse/CLCAD-31)
[CLCAD-7]: https://maplight.atlassian.net/browse/CLCAD-7?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
=> [FEATURE] Add initial filters for public search CLCAD-19

backend/src/utils/upload-ad-disclosure-media.ts, backend/src/utils/upload-file.ts
After testing and merging #26, the [deployment failed](https://cloud.strapi.io/projects/clc-ad-transparency-99273c2e21/deployments/3f869d3e-b8d6-4bab-8c5b-ac71c46641dd) during the file upload process. The error is rather opaque, and only indicates that we are getting a `401` for `Invalid credentials`. This update is an attempt at fixing this error by converting the upload process to use Strapi's Entity Service API instead of interacting with the upload plugin directly. The demo data generation was successful in creating `filingPeriods`, which is also using the Entity Service API. My hope is that this change will allow us to get past this error. While Strapi Cloud does not support multiple environments, we should probably think about what a staging environment would look like for this app, …
=> [BUGFIX] File uploads for demo data generation CLCAD-38

backend/src/index.ts, frontend/app/components/AdDisclosureCard/index.tsx, frontend/app/components/AdDisclosureTable/index.tsx, frontend/app/components/DateSelect/index.tsx, frontend/app/components/Search/FiltersSidebar/SearchFilters/index.tsx, frontend/app/components/Search/SearchBar/index.tsx, frontend/package.json, frontend/yarn.lock
Adds the ability to perform basic date filtering based on the `endDate` of an `adDisclosure`.
=> [FEATURE] Date filtering CLCAD-18

backend/src/index.ts, frontend/app/components/Search/SearchBar/index.tsx
Adds sorting functionality to the frontend public search.
[CLCAD-32](https://maplight.atlassian.net/browse/CLCAD-32)
[CLCAD-32]: https://maplight.atlassian.net/browse/CLCAD-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] Public search sorting CLCAD-32

backend/src/index.ts, frontend/app/components/Search/FiltersSidebar/SearchFilters/index.tsx
#Overview
Adds the ability to search on a target. Achieves this functionality by swapping out the hierarchical menus for refinement lists. This allows search on the target, however, the ability to further refine the search by position is lost. Attributes for targets (e.g. candidate, measure, etc.) are also added to `searchableAttributes` so they are searchable in the main search box.
[CLCAD-75](https://maplight.atlassian.net/browse/CLCAD-75)
[CLCAD-75]: https://maplight.atlassian.net/browse/CLCAD-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] Target search CLCAD-75

backend/src/index.ts, backend/src/utils/constants.ts, frontend/app/components/Search/FiltersSidebar/SearchFilters/index.tsx
Adds the ability to filter by a candidate's office.
[CLCAD-30](https://maplight.atlassian.net/browse/CLCAD-30)
[CLCAD-30]: https://maplight.atlassian.net/browse/CLCAD-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] Filter by office CLCAD-30

frontend/app/components/MenuSelect/index.tsx
Adds an `All` option for the `MenuSelect` component to allow users to clear the selection and update the search results.
[CLCAD-79](https://maplight.atlassian.net/browse/CLCAD-79) 
[CLCAD-79]: https://maplight.atlassian.net/browse/CLCAD-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] Add all option for menu selects CLCAD-79

frontend/app/components/Search/index.tsx
Adds pagination of search results using the Algolia `Pagination` component.
[CLCAD-81](https://maplight.atlassian.net/browse/CLCAD-81)
[CLCAD-81]: https://maplight.atlassian.net/browse/CLCAD-81?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] Search results pagination CLCAD-81
